### PR TITLE
init city

### PR DESCRIPTION
**Pull request by DaikonKing**

### CODE REVIEW

**Review by TankmanGameDev — COMMENTED** [review]
Looks good. But you changed the untitled city, might be a problem

**Comment by starkc1** [comment]
you have a merge conflict

**Comment by starkc1** [comment]
@TankmanGameDev could you approve this

**Comment by TankmanGameDev** [comment]
@starkc1 I don't see an approve button :(

**Review by TankmanGameDev — APPROVED** [review]
Approved!

**Pull request merged**
